apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ include "nginx-rollout-poc.fullname" . }}-validation
spec:
  metrics:
    - name: always-pass
      interval: 5s
      count: 1
      successCondition: result == true
      provider:
        job:
          spec:
            template:
              spec:
                restartPolicy: Never
                containers:
                  - name: check
                    image: busybox
                    command: ["sh", "-c", "exit 0"]
