apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "nginx-rollout-poc.fullname" . }}
spec:
  replicas: {{ .Values.replicas | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "nginx-rollout-poc.name" . }}
  template:
    metadata:
      labels:
{{ include "nginx-rollout-poc.labels" . | indent 8 }}
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config
              mountPath: /usr/share/nginx/html
      volumes:
        - name: config
          configMap:
            name: {{ include "nginx-rollout-poc.fullname" . }}

  strategy:
    blueGreen:
      activeService: {{ include "nginx-rollout-poc.fullname" . }}-active
      previewService: {{ include "nginx-rollout-poc.fullname" . }}-preview
      autoPromotionEnabled: false