apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-rollout-poc.fullname" . }}-preview
  labels:
{{ include "nginx-rollout-poc.labels" . | indent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "nginx-rollout-poc.name" . }}
  ports:
    - port: 80
      targetPort: 80
