replicas: 2

image:
  repository: nginx
  tag: "1.25"

service:
  port: 80

config:
  message: "default message"

workflow:
  enabled: true

  waves:
    - replicas: 1
    - replicas: 3
    - replicas: 6
