components:
  blue:
    replicas: 2
    image: nginx:1.25
    message: "Hello from BLUE"
    port: 80
    strategy:
      type: canary

  green:
    replicas: 1
    image: nginx:1.25
    message: "Hello from GREEN"
    port: 80
    strategy:
      type: bluegreen
